name: Newspaper
main: me.KeybordPiano459.Newspaper.Newspaper
description: A plugin used to inform your users
version: 1.2
softdepend: [Vault]

commands:
  news:
    description: Order a newspaper
    aliases: [newspaper]

permissions:
  newspaper.*:
    description: All permissions
    default: op
    children:
      newspaper.admin: true
  newspaper.admin:
    description: All admin permissions
    default: op